name: workflow trigger

on:
    workflow_dispatch:

    push:
       branches:
          - main
          - '!features/*'        # Does not include feature branches

    pull_request:
        types:
            - opened
            - closed
        paths-ignore:
            - README.md
        branches:
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps: 
            - run: echo this workflow is executed on job/workflow type ${{ github.eventname }}
